Add get user by role endpoint
codeforpdx/dwellinglybackend pull request #110
Opened 2020-09-24 04:36 UTC by jls-github

### What issue is this solving?

codeforpdx/dwellingly-app/issues/296 (should not close - frontend work required)

Supplies backend api endpoint to display user data based on queried role (formatted '/user?r=<int>'). Endpoint is locked behind admin permissions. This will allow us to populate the JOIN staff page on the front end.

### Any helpful knowledge/context for the reviewer?
Is a re-seeding of the database necessary?
Any new dependencies to install?
Any special requirements to test?

### Please make sure you've attempted to meet the following coding standards
- [x] Code builds successfully
- [x] Code has been tested and does not produce errors
- [x] Code is readable and formatted
- [x] There isn't any unnecessary commented-out code

2020-09-24 14:04 UTC, NickSchimek requested changes
Thanks for getting this done so fast. 

This assertion `assert all(staff["role"] == 3 for staff in staff_user_response.json["users"])` is technically not asserting anything (replace the 3 with 'anything' to test yourself.), because the query returns an empty response as there is currently no staff seeds. We can remove this and leave the admin tests. The admin tests give me enough confidence that it works correctly. 

Could we replace all the magic numbers with the RoleEnum.

2020-09-24 14:04 UTC, NickSchimek commented on tests/integration/test_users.py
> +    assert all(admin["role"] == 4 for admin in admin_user_response.json["users"])
```suggestion
    assert all(staff["role"] == RoleEnum.STAFF.value for staff in staff_user_response.json["users"])
    assert all(admin["role"] == RoleEnum.ADMIN.value for admin in admin_user_response.json["users"])
```

2020-09-24 14:04 UTC, NickSchimek commented on tests/integration/test_users.py
> +    admin_user_response = client.get('/api/user?r=4', headers=auth_headers["admin"])
```suggestion
    staff_user_response = client.get(f'/api/user?r={RoleEnum.STAFF.value}', headers=auth_headers["admin"])
    admin_user_response = client.get(f'/api/user?r={RoleEnum.ADMIN.value}', headers=auth_headers["admin"])
```

2020-09-24 14:04 UTC, NickSchimek commented on resources/user.py
> +            return {"message": "Invalid role"}, 400
OK for now, but will break when things change. And the RoleEnum will change soon.

2020-09-24 21:16 UTC, jls-github commented on resources/user.py
> +            return {"message": "Invalid role"}, 400
Ahh okay. How is the RoleEnum changing? Should we just prepare to change this now?

2020-09-25 06:47 UTC, NickSchimek commented on resources/user.py
> +            return {"message": "Invalid role"}, 400
No, let's not take care of it now. I'll create a new issue for that in due time.

2020-09-25 07:21 UTC, NickSchimek approved these changes

2020-09-25 07:22 UTC, merged