Cs ticket 340
codeforpdx/dwellinglybackend pull request #136
Opened 2020-10-29 00:59 UTC by cecillesalazar

### What issue is this solving?
 
Closes codeforpdx/dwellingly-app/issues/340

Fixes bug where passwords are not checked against the database password on password reset.

### Any helpful knowledge/context for the reviewer?

I think there needs to be some frontend changes to accompany this PR. I grokked code in the front end - and as far as I can tell - although we make the user provide the current password along with the new password - I don't think the current password is ever sent to the backend for any sort of comparison. 

So the patch /user/:id endpoint only takes the new password - regardless if the current password matches or not. If someone in the frontend can confirm this - the changePassword component will now have to send in both the current password as well as the new password to the patch request and we will need to create a ticket for that work.

Is a re-seeding of the database necessary?

No

Any new dependencies to install?

No

Any special requirements to test?

None, unless I missed something
 
### Please make sure you've attempted to meet the following coding standards
- [x] Code builds successfully
- [x] Code has been tested and does not produce errors
- [x] Code is readable and formatted
- [x] There isn't any unnecessary commented-out code

2020-10-29 03:43 UTC, NickSchimek commented
Yes, you are right. I checked the frontend and here is a pick of the request payload.

<img width="249" alt="Screen Shot 2020-10-29 at 12 38 23 PM" src="https://user-images.githubusercontent.com/19519317/97522750-d19e1180-19e3-11eb-9291-6d4770fdbcff.png">

The password field is what the new password should be. Hence, this statement `if data['currentPassword'] and data['newPassword']:` will always evaluate to false.

When I created this ticket I just assumed that all fields were being sent from the frontend. Looks like we will need to create a ticket for the frontend to send all fields in the change password form to the backend.

2020-10-29 03:51 UTC, NickSchimek reviewed
I created issue codeforpdx/dwellingly-app/issues/418 to update the frontend. I will hold off on reviewing/merging until frontend is updated. As we may need to make some small changes once the frontend is updated.

2020-11-13 12:02 UTC, NickSchimek requested changes
The frontend PR should be ready to go. You can view it here to see the update. https://github.com/codeforpdx/dwellingly-app/pull/422

It will send the following payload:
```
        current_password: data.current,
        new_password: data.new,
        confirm_password: data.confirm
```

Can you update this PR to use the above payload params. Once this is ready to go then we will get both of them merged at the same time.

2020-11-16 05:06 UTC, cecillesalazar commented
@NickSchimek - ready for another look. Not a big fan that we're mixing camel and snake case for the args - but it seems we're also doing that when we return the json with the `created_at` and `updated_at` fields. Maybe we can clean it up at another ticket just for consistency's sake - but doesn't have to happen on this PR~

2020-11-16 05:30 UTC, NickSchimek commented
When I came on board there was a mixture of camelCase and snake_case. I've been slowly changing everything to snake case where I could easily. It irritates me too. Pep8 style guide says to use snake case, so we should use snake case. I'm fine if people want to submit prs to change terms to snake case, however that can break front end configuration. So it's just been something I ignore and not worry about to much.

2020-11-16 06:51 UTC, NickSchimek commented
I remembered @htharker42 mention we should follow pep8 styling. Here is the paragraph mentioning that snake_case is preferred https://www.python.org/dev/peps/pep-0008/#function-and-variable-names. It would be nice to have some consistency with all the variable names.

2020-11-16 07:16 UTC, NickSchimek requested changes
Looks good. one small change.

2020-11-16 07:16 UTC, NickSchimek commented on resources/user.py
> +          user.hash_digest = UserModel.hash_pw(data['new_password'])
This can be:
```suggestion
          user.password = data['new_password']
```

It is hashed when the user is saved to db.

2020-11-16 09:12 UTC, NickSchimek approved these changes
Thanks for getting this done @cecillesalazar

2020-11-16 09:12 UTC, merged

2020-11-17 06:13 UTC, cecillesalazar commented
@NickSchimek - thanks for the tweak to get it out~