Refactor Hash Password Architecture
codeforpdx/dwellinglybackend pull request #142
Opened 2020-11-10 04:13 UTC by cecillesalazar

### What issue is this solving?

Closes codeforpdx/dwellingly-app/issues/420

### Any helpful knowledge/context for the reviewer?

Nope, just a refactor - simplifying the way we hash/check passwords

Is a re-seeding of the database necessary?

Nope

Any new dependencies to install?

Nope

Any special requirements to test?

Nope

### Please make sure you've attempted to meet the following coding standards
- [x] Code builds successfully
- [x] Code has been tested and does not produce errors
- [x] Code is readable and formatted
- [x] There isn't any unnecessary commented-out code

2020-11-10 15:00 UTC, NickSchimek requested changes
This is great. This handles automatic password hashing when the object is instantiated. However, we also need it for when an object is updated. I pushed up a missing test to expose it. One possible solution is to create getter and setters using pythons built-in decorators.

Something like this? Or do you have another idea?
```
def __init__(self, ...
    ...
    self._password = UserModel.hash_pw(password)
    ...


@property
def password(self):
   return self._password

@password.setter
def password(self, value):
   self._password = UserModel.hash_pw(value)
```

2020-11-12 04:32 UTC, cecillesalazar commented
@NickSchimek - nice catch. Test should be passing now - branch is rebased too~

2020-11-12 06:16 UTC, NickSchimek requested changes
one tiny suggestion.

2020-11-12 06:16 UTC, NickSchimek commented on models/user.py
> +        return bcrypt.checkpw(bytes(plaintext_password, 'utf-8'), self._password)
small detail: I think we should keep this as `self.password` which does end up returning `self._password`, however it is best practice to use getter methods for accessing private fields.

2020-11-12 11:54 UTC, NickSchimek approved these changes
This is great! Thanks for updating this. I will go ahead and make that minor change in a PR to speed up the test suite. I will request your review.

2020-11-12 11:54 UTC, merged