#490 lease with get tenants
codeforpdx/dwellinglybackend pull request #195
Opened 2021-01-13 22:04 UTC by Protopaco

### What issue is this solving?

Resolves the issue covered in #490
codeforpdx/dwellingly-app#490

These changes as a json() method to "leases" model, in order to return information from database as a json.
Also adds lease array to property object and the tenant object when they are returned. 

I attempted to mimic the style and functionality of existing code base.

### Any helpful knowledge/context for the reviewer?
Is a re-seeding of the database necessary?
Any new dependencies to install?
Any special requirements to test?

### Please make sure you've attempted to meet the following coding standards
- [ ] Code builds successfully
- [ ] Code has been tested and does not produce errors
- [ ] Code is readable and formatted
- [ ] There isn't any unnecessary commented-out code

2021-01-15 05:47 UTC, Chris-Boe requested changes

2021-01-15 05:47 UTC, Chris-Boe commented on Pipfile
> +black = "*"
It looks like we already have this listed under dev-packages. Do we need it here for some reason?

2021-01-15 15:57 UTC, Protopaco commented on Pipfile
> +black = "*"
No, it must have been added automatically while I was adding Black to my system.  Sorry about that!

2021-01-16 07:30 UTC, Chris-Boe approved these changes

2021-01-16 07:31 UTC, merged