Updated CONTRIBUTING.md with an additional Mac troubleshooting suggestion
codeforpdx/dwellinglybackend pull request #202
Opened 2021-01-20 22:02 UTC by russellneville

On Mac based on an exception encountered with an old version of pipenv.  running setup step 6: `pipenv run flask db create` with pipenv version 2018.11.14 resulted in an `AttributeError: can't set attribute exception`.

### What issue is this solving?

Closes codeforpdx/dwellingly-app/issues/510

### Any helpful knowledge/context for the reviewer?
Is a re-seeding of the database necessary?
No
Any new dependencies to install?
No
Any special requirements to test?
No

### Please make sure you've attempted to meet the following coding standards
- [x] Code builds successfully
- [x] Code has been tested and does not produce errors
- [x] Code is readable and formatted
- [x] There isn't any unnecessary commented-out code

2021-01-21 03:37 UTC, aedwardg approved these changes
Awesome, thanks for adding this tip @russellneville 👍

2021-01-24 01:28 UTC, Chris-Boe requested changes
There aren't any pip dependency changes in this PR so we can probably just undo the changes to the pipfile.lock file instead of resolving the merge conflicts

2021-02-21 17:46 UTC, NickSchimek requested changes
@russellneville Thanks for the PR. Can we get this updated to document the specific error that was seen, and let's remove the Pipfile as that file should not have been changed. Thanks!

2021-02-21 17:46 UTC, NickSchimek commented on CONTRIBUTING.md
> +
Can you document the specific errors that were seen here. There are many different errors that can happen, and documenting specific errors can be helpful.

2021-02-27 17:22 UTC, closed without merging

2021-02-27 17:22 UTC, NickSchimek commented
Closed since this is stable. Feel free to reopen