Update ticket model & schema
codeforpdx/dwellinglybackend pull request #276
Opened 2021-05-19 02:26 UTC by aedwardg

## Description

Updates the ticket model and schema.
Renames db fields for clarity and removes `noteslog` and `assignedUserID`.
The assigned users will now be the staff members who are assigned to the ticket's tenant.
Rather than returning a user id, the `json` method will now return a list json objects representing all assigned staff members.

@NickSchimek let me know if I should add some sort of validation to make sure the `creator_id` is the current user.  Also note that the ticket integration tests are pretty bad.  These should probably be addressed in another issue.

### What issue is this solving?

Closes codeforpdx/dwellingly-app/issues/614

_NOTE: DB needs to be re-seeded for this._

2021-05-24 10:13 UTC, NickSchimek requested changes
This looks good. Just have a few small changes. Thanks!

2021-05-24 10:13 UTC, NickSchimek commented on models/tickets.py
>      urgency = db.Column(db.String(12))
I'm not sure if I mentioned it, but we would like all of these fields to be required. Since we're using marshmallow's auto schema we can add the `nullable=False` to achieve that in the validations and at the database level.

2021-05-24 10:13 UTC, NickSchimek commented on models/user.py
> +        primaryjoin=id == TicketModel.creator_id,
I wasn't aware we were using the term `author` here. Instead of using `creator_id` lets change that to `author_id` to be consistent with the terminology already being used.

2021-05-24 10:13 UTC, NickSchimek commented on schemas/ticket.py
> +    author = fields.Nested("UserSchema")
I forget what this does. Is this for serialization? Do we need it? Should we remove it?

2021-05-24 10:13 UTC, NickSchimek commented on tests/factory_fixtures/ticket.py
> +        ticket = TicketModel(**ticket_attributes(issue, tenant, create_join_staff()))
Since we're modifying this lets update it to use the create method instead of bypassing schema validations.

2021-05-24 21:55 UTC, aedwardg commented on schemas/ticket.py
> +    author = fields.Nested("UserSchema")
I know that this is used for Marshmallow serialization.  I'm not 100 percent sure if it does anything else.  I know we've been doing this for the fields that have a db relationship with another field but I don't know that it's necessary outside of serialization.

2021-05-24 22:01 UTC, aedwardg commented
Made all the requested changes, but I did not remove the nested fields in the schema.

2021-05-30 04:07 UTC, NickSchimek commented on schemas/ticket.py
> +    def validate_creator(self, value):
this probably should be validate_author

2021-05-30 04:07 UTC, NickSchimek commented on tests/factory_fixtures/ticket.py
> +    def _ticket_attributes(issue, tenant, creator):
probably author here too

2021-05-30 04:23 UTC, NickSchimek approved these changes
Thanks!

2021-05-30 04:24 UTC, merged