Issue619
codeforpdx/dwellinglybackend pull request #279
Opened 2021-05-19 21:05 UTC by Chris-Boe

## Description
Fixes some test data and uses the schema's create functionality in the ticket POST method

### What issue is this solving?

Closes codeforpdx/dwellingly-app/issues/619

2021-05-19 21:15 UTC, Chris-Boe commented on resources/tickets.py
> +        return {"message": "Ticket successfully created"}, 201
We are not using the returned JSON of the created ticket at all in the frontend (PR: https://github.com/codeforpdx/dwellingly-app/pull/611) so I changed this to just return a success message

2021-05-23 00:07 UTC, NickSchimek requested changes
Thanks for the PR. We have someone fixing the seed file in a different issue. Rather than modifying the seed file. I would prefer to disconnect the test from the seed file by using factories.

2021-05-29 23:29 UTC, NickSchimek commented on tests/integration/test_tickets.py
> +    assert response.json == {"message": "Ticket successfully created"}
There is still some work that needs to be done with this test, but I will go ahead and merge for now. This test isn't actually testing anything useful. It's just testing that we return json, but not actually testing that we called the create method. See the discussion here: https://github.com/codeforpdx/dwellinglybackend/pull/275#discussion_r637637833

2021-05-29 23:30 UTC, NickSchimek approved these changes
Thanks!

2021-05-29 23:31 UTC, merged