Refactor tickets integration tests
codeforpdx/dwellinglybackend pull request #310
Opened 2021-06-06 09:33 UTC by aedwardg

## Description

Replaces `auth_headers` with `valid_header` and refactors all tests in the file.

All tests are now separated into appropriate classes, which inherit fixtures and endpoint from a base configuration class.
Methods are stubbed out where appropriate, but I couldn't figure out a nice way to test the delete action here using the patch, so those tests still hit the endpoint.

### What issue is this solving?

Closes codeforpdx/dwellingly-app/issues/597

2021-06-06 12:45 UTC, NickSchimek commented on tests/integration/test_tickets.py
> +
This is great! I like this design pattern! Good work!

2021-06-13 10:03 UTC, NickSchimek requested changes
Thanks @aedwardg  - These look great. I just have a few organizational comments. 1 sassy comment, and a 1 off the rails comments.

2021-06-13 10:03 UTC, NickSchimek commented on tests/integration/test_tickets.py
> +    def test_tickets_get_one(self, valid_header, create_ticket):
This method is testing the endpoint `tickets/:id` so I think for readability lets put it in a separate class than the methods testing the endpoint `tickets`. <- Since both endpoints hit a completely different class and method then they should be in a separate class in the test. So I think the class would be named using the singular version `TestTicketGET` and the method can simply be `test_get`.

2021-06-13 10:03 UTC, NickSchimek commented on tests/integration/test_tickets.py
> +        assert response.json == {"tickets": [ticket_1.json()]}
As a side note: I always find this a bit hard to parse. 
```python
    def get(self):
        if request.args and request.args["tenant_id"]:
            return {
                "tickets": TenantModel.find(request.args["tenant_id"]).tickets.json()
            }
        else:
            return {"tickets": TicketModel.query.json()}
```

If you want to see if this can be refactored to be simpler than I would accept that in this PR too.
What I would like to see is something like this.
```python
tickets = TicketModel.query
if tenant_id:
  tickets = tickets.where(tenant_id: tenant_id)
return tickets.json()
```

What I like about this is that the context always focuses on the return value (tickets). Where as the other one Focuses on Tenants first, and I find myself checking to see which file I'm reading, and asking why is it trying to find a Tenant when its serializing tickets. Obviously I need to read the next few commands and figure it out, but for someone who doesn't see this code as often as I do would likely get confused too the first time they come about it. So if possible I would like to make it simpler to read at some point in the future.

I think sqlalchemy has methods to do that. Or we can make our own wrappers to whatever they provide.

2021-06-13 10:03 UTC, NickSchimek commented on tests/integration/test_tickets.py
> +        new_ticket = {
We should create a factory for this if we don't already have on that returns valid ticket attributes.

2021-06-13 10:03 UTC, NickSchimek commented on tests/integration/test_tickets.py
> +class TestTicketsPUT(BaseConfig):
Let's name this TestTicketPUT. Since the class we're testing is the `Ticket` class.

2021-06-13 10:03 UTC, NickSchimek commented on tests/integration/test_tickets.py
> +class TestTicketsDELETE(BaseConfig):
Same as what I said above for the get endpoint. Let's split these tests to separate the different methods we're testing. One class for each method.

2021-06-13 10:03 UTC, NickSchimek commented on tests/integration/test_tickets.py
> +        assert TicketModel.query.all() == []
Whenever we call the database. We need to refresh the session 😉 ha I know you know this already. :-)

2021-06-17 02:24 UTC, aedwardg commented on tests/integration/test_tickets.py
> +        assert response.json == {"tickets": [ticket_1.json()]}
Updated this, take a look and let me know what you think

2021-06-17 02:28 UTC, aedwardg commented on tests/integration/test_tickets.py
> +        new_ticket = {
I went ahead and updated the `ticket_attributes` factory in this PR so I could get rid of that manual one.  Let me know if that works for you

2021-06-19 11:16 UTC, NickSchimek commented on resources/tickets.py
> +        return {"tickets": tickets.json()}
😄

2021-06-19 11:20 UTC, NickSchimek commented on tests/factory_fixtures/ticket.py
> +            "author_id": author.id if author else create_join_staff().id,
<img width="468" alt="why aren't you display???" src="https://media.giphy.com/media/AEzIKaaOTkO9eyGUDK/giphy.gif">

2021-06-19 11:27 UTC, NickSchimek approved these changes
Looks great! I really like that `where`. Makes it a lot simpler to understand what's going on.

Thanks for making those additional updates!

2021-06-19 11:27 UTC, merged