update revoked_token id field type
codeforpdx/dwellinglybackend pull request #342
Opened 2021-07-18 15:14 UTC by 13528080556

## Description

### What issue is this solving?
fix 662

Closes codeforpdx/dwellingly-app/issues/###

2021-07-19 03:54 UTC, NickSchimek commented
Yeah, This change will work. I don't think we need the jti column anymore if we're going to store the jti as the id of the table.

I'm a bit hesitant to approve this without checking how this model is used in the application. It seems the original implementation meant for the jti column to be used, but obviously that is not what's being done. Perhaps this change is Okay though. Did you find anything to suggest otherwise?

2021-07-19 13:31 UTC, 13528080556 commented
> Yeah, This change will work. I don't think we need the jti column anymore if we're going to store the jti as the id of the table.
> 
> I'm a bit hesitant to approve this without checking how this model is used in the application. It seems the original implementation meant for the jti column to be used, but obviously that is not what's being done. Perhaps this change is Okay though. Did you find anything to suggest otherwise?



I think the original meaning of the program is to blocktlist n the future
However, there is currently no move to blacklist the token in the program.

2021-07-26 08:18 UTC, NickSchimek requested changes
When a user logs out we should store their jwt in this table, unfortunately there is no logic that I can see that handles logging out a user. I'm not sure how all this was initially setup with the frontend, but that does seem incorrect.

I don't think changing the column types to make the test pass is the correct solution.

If you look at app.py you will find the following code which calls `is_jwt_blacklisted`

https://github.com/codeforpdx/dwellinglybackend/blob/6307272acdf11ef542f0ddd9b96fc363855ac45c/app.py#L48-L51

And if you look at that method you might be able to see why there is an error:

https://github.com/codeforpdx/dwellinglybackend/blob/6307272acdf11ef542f0ddd9b96fc363855ac45c/models/revoked_tokens.py#L11-L13

It is callling the method `get` with the jwt string. get is not what we want to use here as it looks up by the id column. But we want to find a row in the table by the jwt column.

2021-07-26 08:18 UTC, NickSchimek commented on models/revoked_tokens.py
> +    id = db.Column(db.String(36), primary_key=True)
I don't think the solution is to change the id field to a String. That does make the test pass, but will cause other issues that we are apparently missing tests for.

2021-08-01 21:38 UTC, merged