704/remove backend dependency
codeforpdx/dwellinglybackend pull request #386
Opened 2021-10-12 05:23 UTC by TNorbury

### What issue is this solving?
Please connect this Pull Request to the issue it is resolving by using the controls on the right side of this PR.
closes codeforpdx/dwellingly-app#704 

### Any helpful knowledge/context for the reviewer?
This doesn't provided any change in behavior, it was rather just a re-assigning of who was responsible for what data. Now the frontend handles widget information such as the title, link, and labels. Whereas the backend is just concerned with providing the raw data.

There is a complementary PR in the frontend repo that'll need to be closed at the same time:  codeforpdx/dwellingly-app#710

2021-10-12 18:01 UTC, TNorbury commented
The failed test will be fixed by #385

2021-10-17 03:20 UTC, NickSchimek requested changes
Thank You! - I think this looks good.

@Chris-Boe Since this change impacts the front-end, can you give this a review?

I've requested a couple small changes to the test file.

2021-10-17 03:20 UTC, NickSchimek commented on tests/integration/test_widgets.py
> +        widgetResponse = self.client.get("/api/widgets", headers=header)
Thanks for writing tests! Let's simplify this as login is already well tested, and it will make the test a bit easier to read.
```suggestion
    def test_get_widgets(self, valid_header):
        widgetResponse = self.client.get("/api/widgets", headers=valid_header)
```

2021-10-17 03:20 UTC, NickSchimek commented on tests/integration/test_widgets.py
> +        assert widgetResponse.status_code == 200
style: Let's use snake_case instead of camelCase in the backend where possible

2021-10-17 03:24 UTC, Chris-Boe commented
> Thank You! - I think this looks good.
> 
> @Chris-Boe Since this change impacts the front-end, can you give this a review?
> 
> I've requested a couple small changes to the test file.

Yeah I plan on testing this with the frontend PR this weekend! Should get to it tomorrow after I finish up my own PR's

2021-10-17 13:51 UTC, NickSchimek approved these changes

2021-10-19 05:18 UTC, Chris-Boe approved these changes

2021-10-19 05:24 UTC, merged