Widgets endpoint
codeforpdx/dwellinglybackend pull request #78
Opened 2020-08-23 21:41 UTC by htharker42

### What issue is this solving?
Add CreatedDate to User model #272

### Any helpful knowledge/context for the reviewer?
Is a re-seeding of the database necessary? YES
Any new dependencies to install? NO
Any special requirements to test? NO

### Please make sure you've attempted to meet the following coding standards
- [X] Code builds successfully
- [X] Code has been tested and does not produce errors
- [X] Code is readable and formatted
- [X] There isn't any unnecessary commented-out code

2020-08-27 10:11 UTC, NickSchimek commented on models/tickets.py
> +        # dateTimeStatusChange = datetime.strptime(self.updated, "%d-%b-%Y (%H:%M)")
Do we need this commented out code here?

2020-08-27 10:11 UTC, NickSchimek commented on resources/tickets.py
> +    # @jwt_required
Should these be commented out? Or can they be deleted completely?

2020-09-01 08:08 UTC, htharker42 commented on models/tickets.py
> +        # dateTimeStatusChange = datetime.strptime(self.updated, "%d-%b-%Y (%H:%M)")
nope, it was left over from some of the changes to the DateTime vars I made

2020-09-01 08:08 UTC, htharker42 commented on resources/tickets.py
> +    # @jwt_required
doh! thought I remembered to go back and fix these

2020-09-02 22:52 UTC, Chris-Boe requested changes
Looks good, just got some merge conflicts and some failing tests (that will probably be fixed when the branch is updated)

2020-09-04 03:44 UTC, Chris-Boe requested changes
Looks like we got some tests failing on the branch and the PR https://travis-ci.com/github/codeforpdx/dwellinglybackend/jobs/380639930

2020-09-04 05:30 UTC, zfregin commented
It looks like this needs to merge the latest changes from the request-access branch. Those changes enable JSON serialization of the RoleEnum

2020-09-12 22:08 UTC, closed without merging

2020-09-12 22:09 UTC, htharker42 commented
issues with rebasing causing errors in code
created new branch - re implemented changes